<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">

<head>
   <title>RRMart - Privacy Policy</title>
      <%@include file="./menu/head.jsp"%>
   <style>
      ul,
      ol {
         padding-left: 10px;
      }

      .content p,.content ul li {
         text-align: justify;
      }
      .dark td,.dark th{
         color : white;
      }
   </style>
</head>

<body>
  
   <div class="osahan-help">
      <div class="p-3 border-bottom bg-white">
         <div class="d-flex align-items-center">
            <a class="font-weight-bold text-danger text-decoration-none" href="/terms">
               <i class="icofont-rounded-left back-page"></i></a>
            <h6 class="font-weight-bold m-0 ml-3">Privacy Policy</h6>
            <a class="toggle ml-auto" href="#"><i class="icofont-navigation-menu"></i></a>
         </div>
      </div>
   </div>
   <div class="p-3 mb-5">
      <h4 class="mb-3 ">Privacy Policy</h4>
      <div class="content">
        
         <p>The portal&nbsp;www.rrmart.in and its corresponding mobile application (collectively, “RR Mart&nbsp;”),
            is managed and operated by Rapture Retail Private Limited&nbsp;(“&nbsp;RR”, “we”, “us” or “our”). Any
            natural or legal person who accesses and/or uses RR Mart in any manner (“you” or “&nbsp;your”) or
            uses any current or future service or functionality or offer made available on RR Mart
            (“Service&nbsp;”) will be subject to these terms and conditions for use of RR Mart (“&nbsp;Terms of
            Use”), as updated from time to time and such terms, guidelines and conditions as may be
            applicable to such Service (“&nbsp;Service Terms”). If these Terms of Use are inconsistent with
            such Service Terms, the Service Terms will control to the extent of such inconsistency with
            respect to the applicable Service.</p>
         <p>These Terms of Use constitute an electronic record within the meaning of the applicable law.
            This electronic record is generated by a computer system and does not require any physical
            or digital signatures. Please read these Terms of Use carefully before using or accessing RR
            Mart or availing any Service. By using the RR Mart or availing any Service, you signify your
            agreement to be bound by these Terms of Use.</p>

         <ol>
            <li><span class="font-weight-bolder">USE OF RR MART</span><br>
               <p>You agree and acknowledge that RR Mart is an online platform that enables you to
                  purchase the products listed on RR Mart at the indicated price at any time from the
                  serviceable locations . Except where we are the seller of the relevant product on RR
                  Mart, you agree and acknowledge that we are only a facilitator and are not and
                  cannot be a party to or control in any manner any transactions on RR Mart.
                  Accordingly, such contract of sale of products on the website shall be a strictly
                  bipartite contract between you and the sellers on RR Mart.</p>
            </li>
            <li><span class="font-weight-bolder">ELIGIBILITY</span><br>
               <p>
                  Only persons who can enter into legally binding contracts as per Indian Contract
                  Act, 1872, i.e. persons who are 18 years of age or older, are of sound mind, and are
                  not disqualified from entering into contracts by any law, can use and access RR
                  Mart. If you are a minor i.e. under the age of 18 years, you may use RR Mart only
                  with the involvement of a parent or guardian.
               </p>
            </li>

            <li><span class="font-weight-bolder">REGISTRATION AND OPERATION OF YOUR ACCOUNT</span><br>
               <p>
               </p>
               <ul class="mt-2">
                  <li>
                     In order to use RR Mart and avail the Services, you will have to register on RR
                     Mart. Registration is a one-time process and is free of cost. You may register
                     in one of the following ways:

                     <ul class="mt-4">
                        <li>
                           <span class="font-weight-bolder">By creating a RR Mart account:&nbsp;</span><br>
                           <p>
                              You can register by providing relevant information, such as your name, gender, and such
                              other details relevant for creating an account. Your login ID and password will be created
                              basis the information provided by you, which you can use to access your RR Mart account at
                              any time.
                           </p>
                        </li>
                        <li>
                           <span class="font-weight-bolder">By using a third-party account:&nbsp;</span><br>
                           <p>
                              You may use the login credentials from any third-party accounts maintained by you, as
                              identified by RR (for example, Google or Facebook). If you use such third party account,
                              you will also be subject to specific terms and conditions applicable to such account, as
                              may be imposed by the relevant third-party.
                           </p>
                           <p>
                              Your credentials shared by you at the time of registration and your RR Mart login ID and
                              password are referred to as <b>“&nbsp;Account Information”</b>.
                           </p>
                        </li>
                     </ul>
                  </li>
                  <li>
                     You are solely authorized to operate the account created by you. Consequently, it is your
                     responsibility to maintain the confidentiality of the Account Information and for restricting
                     access to your computer/mobile/other similar devices to prevent unauthorized access to your
                     account. You will at all times keep your Account Information current and accurate. You can access
                     and update much of the Account Information you provided us with in the&nbsp;‘Your
                     Account’&nbsp;area of the website.
                  </li>
                  <li>
                     You will:
                     <p class="mb-1 ml-4">(a) immediately inform RR of any unauthorized use of the account or any other
                        security breach; and</p>
                     <p class="mb-1  ml-4">
                        (b) ensure that you log out of your account at the end of each session. RR will not be liable
                        for any loss or direct or indirect damage arising from your failure to comply with these Terms
                        of Use. You may be held liable for any losses incurred to RR or any other user due to
                        unauthorized use of their account, resulting from your failure to keep your Account Information
                        safe, secure and confidential. We reserve the right to refuse access to RR Mart, terminate
                        accounts, remove or edit content at any time without notice to you.
                     </p>

                  </li>
               </ul>
               <p></p>

            </li>
            <li><span class="font-weight-bolder">COMMUNICATION AND UNSUBSCRIPTION</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     You understand that once you have shared your Account Information and successfully registered on RR
                     Mart, you may receive SMS or email notifications from RR relating to your registration and
                     transactions on RR Mart.
                  </li>
                  <li>
                     You may also receive such notifications regarding any marketing / promotional activities that maybe
                     available on RR Mart from time to time. By sharing your Account Information and registering on RR
                     Mart and/ or verifying your contact number with us, you explicitly consent to receive marketing/
                     promotional communications (through call, SMS, email or other digital and electronic means) from us
                     and/or our authorized representatives regarding any new services or offerings, even if your contact
                     number is registered under the DND/NCPR list under the Telecom Commercial Communications Customer
                     Preference Regulations, 2018.
                  </li>
                  <li>
                     RR may also send notifications and reminders with respect to the Services on RR Mart. While RR
                     endeavors to provide these notifications and reminders to you promptly, RR does not provide any
                     guarantee and will not be held liable or responsible for any failure to send such
                     notifications/reminders to you.
                  </li>
                  <li>
                     You can unsubscribe / opt-out from receiving marketing/ promotional communications, newsletters and
                     other notifications from RR at any time by following the instructions set out in such
                     communications.
                  </li>
               </ul>
               <p></p>
            </li>
            <li><span class="font-weight-bolder">LICENSE AND ACCESS TO PLATFORM</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     Your use of RR Mart, the Services, and access to the RR Mart Content (&nbsp;as defined below) is
                     subject to a limited, revocable and non-exclusive license which is granted to you when you register
                     on RR Mart. You will use RR Mart solely for identifying products, carrying out purchases of
                     products and processing returns and refunds, in accordance with&nbsp;<b>Return and Refund
                        Policy</b>, for your personal use only and not for business purposes.
                  </li>
                  <li>
                     The license granted to you does not include a license for:
                     <p class="mb-1  ml-4">(a) resale of Products or commercial use of RR Mart or RR Mart Content, </p>
                     <p class="mb-1  ml-4">(b) any collection and use of product listings, description, or prices, </p>
                     <p class="mb-1  ml-4">(c) any use of RR Mart, the Services and/or of RR Mart Content other than as
                        contemplated in these Terms of Use, </p>
                     <p class="mb-1  ml-4">(d) any downloading or copying of Account Information, </p>
                     <p class="mb-1  ml-4">(e) any use of data mining, robots, or similar data gathering and extraction
                        tools to extract (whether once or many times) any parts of RR Mart, </p>
                     <p class="mb-1  ml-4">(e) creating and/ or publishing your own database that features parts of RR
                        Mart.</p>

                  </li>
                  <li>
                     You grant to RR a royalty-free, perpetual, irrevocable, non-exclusive right and license to adopt,
                     publish, reproduce, disseminate, transmit, distribute, copy, use, create derivative works from,
                     display worldwide, or act on any material posted by you on RR Mart without additional approval or
                     consideration in any form, media, or technology now known or later developed, for the full term of
                     any rights that may exist in such content, and you waive any claim over all feedback, comments,
                     ideas or suggestions or any other content provided through or on RR Mart. You agree to perform all
                     further acts necessary to perfect any of the above rights granted by you to RR, including the
                     execution of deeds and documents, at its request.
                  </li>
                  <p>Please note that RR at all times reserves the right to refuse your access to RR Mart,
                     terminate/deactivate your account, remove or edit content on RR Mart, at its discretion.</p>
               </ul>
               <p></p>
            </li>

            <li><span class="font-weight-bolder">PERSONAL INFORMATION PRIVACY&nbsp;</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        During the course of your registration on and usage of RR Mart or availing the Services, RR may
                        collect and store and/or you may provide us with, personal identifiable and sensitive
                        information about you, including without limitation your name, phone number, email address,
                        address, postal code, occupation, login details etc.
                     </p>
                  </li>
                  <li>
                     <p>
                        RR respects the sensitivity of the information about you and we appreciate your trust in us. In
                        this regard, RR has formulated the&nbsp;Privacy Policy,&nbsp;which shall be deemed to be
                        included in these Terms of Use, setting out the manner in which your information is collected,
                        stored, processed, used and disclosed. If you object terms of our Privacy Policy, please do not
                        use or access RR Mart or avail the Services. For more information, please refer to
                        the&nbsp;Privacy Policy.
                     </p>
                  </li>
               </ul>
               <p></p>
            </li>

            <li><span class="font-weight-bolder">CONTENT ON PLATFORM</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        All information, content, material, text, graphics, images, logos, button icons, software code,
                        interface, design and the collection, arrangement and assembly of the content on RR Mart or any
                        of the other Services are the property of RR or its affiliates <b> (“RR Mart Content”), </b> and
                        are protected under copyright, trademark and other applicable laws. Further, all trademarks,
                        services marks, trade names and trade secrets in relation to RR Mart whether or not displayed on
                        RR Mart, are proprietary to RR.
                     </p>
                  </li>
                  <li>
                     <p>
                        RR may display on RR Mart any third-party logos, trade names, trademarks of other brands, as per
                        the license granted to RR by such brands.
                     </p>
                  </li>
                  <li>
                     <p>
                        No information, content or material from RR Mart (including the RR Mart Content) may be copied,
                        reproduced, republished, duplicated, copied, sold, resold, uploaded, posted, transmitted,
                        distributed or otherwise exploited in any way (including for any commercial purpose) without
                        RR’s express written permission. You will not frame or use framing techniques to enclose any
                        trademark, logo, or other proprietary information (including images, text, page layout, or form)
                        of RR and its affiliates without express written consent. You may not use any meta tags or any
                        other “hidden text” utilizing RR’s or its affiliates’ names or trademarks without the express
                        written consent of RR and/or its affiliates, as applicable. Any unauthorized use terminates the
                        permissions granted in these Terms of Use.
                     </p>
                  </li>
               </ul>
               <p></p>
            </li>

            <li><span class="font-weight-bolder">&nbsp;DISCLAIMERS&nbsp;</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        RR will try to make access to and use of RR Mart error-free and without interruptions. However,
                        your access to RR Mart may be occasionally suspended or restricted to allow for repairs,
                        maintenance, or for introduction of new facilities or services on RR Mart. RR does not take
                        responsibility for any access or usage problems that arise from internet related issues at your
                        end.
                     </p>
                  </li>
                  <li>
                     <p>
                        All information in relation to third parties, including sellers and the products listed by them
                        on RR Mart<b> (“&nbsp;Third Party Information”)</b> are provided only for reference. RR, in its
                        capacity of an intermediary under the applicable laws, is not endorsing Third Party Information
                        and is not responsible for any errors and representation nor is it associated with it and you
                        shall access the Third Party Information at your own risk.
                     </p>
                  </li>
                  <li>
                     <p>
                        RR Mart may contain user generated content which RR does not pre-screen and which contains views
                        that may be opinions of users/ experts. RR will do its best to monitor, edit or remove such user
                        generated content where it is necessary to do so (for instance, if such content violates these
                        Terms of Use). RR does not promise that the user generated content on RR Mart is accurate,
                        complete or updated, that it will not offend or upset any person or that it does not infringe
                        the intellectual property rights of third parties.
                     </p>
                  </li>
                  <li>
                     <p>
                        To help you in identifying the products of your choice, description of the products are provided
                        on RR Mart by the relevant seller through photographs, videos, charts, screenshots, infographics
                        and other visual aids. While reasonable efforts are made to provide accurate visual
                        representations, the appearance/color of the products when delivered may differ for various
                        reasons.
                     </p>
                  </li>
                  <li>
                     <p>
                        The Services included on RR Mart are provided on an “as is” and “as available” basis without any
                        representations or warranties, express or implied, except as otherwise specified in writing. RR
                        does not covenant or provide any representations and warranties:
                     </p>

                     <ul>
                        <li>
                           <p>In respect of quality, suitability, accuracy, reliability, performance, safety,
                              merchantability, fitness for a particular purpose/consumption or the content (including
                              product or pricing information and/or specifications) on RR Mart.</p>
                        </li>
                        <li>
                           <p>That the Services will be made available at all times.</p>
                        </li>
                        <li>
                           <p>That the operation of RR Mart, including the functions contained in any content,
                              information and materials on RR Mart or any third-party sites or services linked to RR
                              Mart will be uninterrupted, or that the defects will be rectified, or that RR Mart or the
                              servers that make such content, information and materials available are free of viruses or
                              other harmful components, and</p>
                        </li>
                        <li>
                           <p>That the RR Mart Content available on RR Mart is complete, true, accurate or
                              non-misleading.</p>
                        </li>
                     </ul>
                  </li>
                  <li>
                     <p>
                        Parties other than RR and its affiliates may operate stores, provide services, or list or sell
                        product lines on RR Mart. We are not responsible for examining or evaluating, and we do not
                        warrant or endorse the offerings of any of these businesses or individuals, or the content made
                        available by them. RR does not assume any responsibility or liability for the actions, products,
                        and content of any of these and any other third-parties. The information displayed on RR Mart is
                        for informational purpose only, and does not amount to or be deemed to be an endorsement of any
                        product or service under any circumstances.
                     </p>
                  </li>
                  <li>
                     <p>
                        To the extent permitted by applicable law, RR disclaims any liability against any loss, damage,
                        expenses, liabilities, claim, injury caused due to the failure of performance, omission, defect
                        of products, or deletion, interruption, error, delay, virus, communication, unauthorised access,
                        theft, destruction, alteration or use of records on RR Mart.
                     </p>
                  </li>
                  <li>
                     <p>
                        RR is not responsible for the content of any third party sites and does not make any
                        representations regarding the content or accuracy of material on such sites. If you decide to
                        access links of any third party platforms, you are doing so entirely at your own risk and
                        expense.
                     </p>
                  </li>
               </ul>
               <p></p>
            </li>

            <li><span class="font-weight-bolder">USER WARRANTIES AND RESTRICTIONS</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        You represent and warrant that: (a) your use of RR Mart and/or Services will not violate any
                        applicable law or regulation; (b) all information that is submitted to RR in connection with RR
                        Mart and/or Services is true, accurate and lawful; (c) use of the content and material you
                        supply does not breach any applicable RR Mart policies or guidelines and will not cause injury
                        to any person or entity (including that the content or material is not defamatory). If at any
                        time, the information provided by you is found to be false or inaccurate, RR will have the right
                        to reject registration, cancel all orders, and restrict you from using the Services and other
                        affiliated services in the future without any prior intimation whatsoever. You agree to
                        indemnify RR and its affiliates for all claims brought by a third party against it or its
                        affiliates arising out of or in connection with a breach of any of these warranties.
                     </p>
                  </li>
                  <li>
                     <p>
                        You will use RR Mart for lawful purposes only, and will not undertake any activity that is
                        harmful to RR Mart or its content or otherwise not envisaged through RR Mart. You have a limited
                        license to access and use RR Mart, solely for the purpose of availing the Services, subject to
                        these Terms of Use.
                     </p>
                  </li>
                  <li>
                     <p>
                        The use of the Platform by you is restricted to personal use only, and you will not use any
                        portion of RR Mart (including the contents on the Platform) or Services for any resale or
                        commercial purpose.
                     </p>
                  </li>
                  <li>
                     <p>
                        You will not do any of the following:

                     </p>
                     <ul>
                        <li>
                           <p>Delete or modify any content on RR Mart, such as any information regarding the Services,
                              their performance, sales or pricing;</p>
                        </li>
                        <li>
                           <p>Use any engine, software, tool, agent or other mechanism (such as spiders, robots,
                              avatars, worms, time bombs etc.) to navigate or search RR Mart.</p>
                        </li>
                        <li>
                           <p>
                              Make false or malicious statements against the Services, RR Mart or RR
                           </p>
                        </li>
                        <li>
                           <p>
                              Post, copy, submit, upload, distribute, or otherwise transmit or make available any
                              software or other computer files that contain a virus or other harmful component, or
                              otherwise disrupt or damage RR Mart and/or Services or any connected network, or otherwise
                              interfere with any person or entity's use or enjoyment of RR Mart and/or the Services
                           </p>
                        </li>
                        <li>
                           <p>
                              Introduce any trojans, viruses, any other malicious software, any bots or scrape RR Mart
                              for any information.
                           </p>
                        </li>
                        <li>
                           <p>
                              Probe, scan, or test the vulnerability of any system, security or authentication measures
                              implemented by us or otherwise tamper or attempt to tamper with our technological design
                              and architecture.
                           </p>
                        </li>
                        <li>
                           <p>
                              Hack into or introduce malicious software of any kind onto RR Mart
                           </p>
                        </li>
                        <li>
                           <p>
                              Gain unauthorized access to, or interfere with, or damage, or disrupt the server on which
                              the details connected to the Services are stored, or any other server, computer, or
                              database connected to the Services; or
                           </p>
                        </li>
                        <li>
                           <p>
                              Engage in any form of antisocial, disruptive, or destructive acts, including “flaming,”
                              “spamming,” “flooding,” “trolling,”, “phishing” and “griefing” as those terms are commonly
                              understood and used on the internet.
                           </p>
                        </li>


                     </ul>
                     <p></p>
                  </li>
                  <li>
                     <p>
                        You are prohibited from hosting, displaying, uploading, modifying, publishing, transmitting,
                        updating or sharing on or through RR Mart, any information that:
                     </p>
                     <ul>
                        <li>
                           <p>
                              Belongs to another person and to which you do not have any right.
                           </p>
                        </li>
                        <li>
                           <p>
                              Is harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic,
                              invasive of another’s privacy, hateful, relating to or encouraging money laundering or
                              gambling, or otherwise harmful in any manner whatsoever.
                           </p>

                        </li>
                        <li>
                           <p>
                              Harms minors in any way.
                           </p>
                        </li>
                        <li>
                           <p>
                              Infringes any patent, trademark, copyright or other proprietary rights.
                           </p>
                        </li>
                        <li>
                           <p>
                              Volates any law for the time being in force
                           </p>
                        </li>
                        <li>
                           <p>Deceives or misleads the addressee about the origin of such messages or communicates any
                              information which is grossly offensive or menacing in nature</p>
                        </li>
                        <li>
                           <p>Impersonates or defames another person; or</p>
                        </li>
                        <li>
                           <p>
                              Contains software viruses or any other computer code, files or programs designed to
                              interrupt, destroy or limit the functionality of any computer resource.
                           </p>
                        </li>
                     </ul>
                  </li>
               </ul>
               <p></p>
            </li>


            <li><span class="font-weight-bolder">INDEMNIFICATION AND LIMITATION OF LIABILITYs</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        You agree to indemnify, defend and hold harmless RR, its affiliates, officers, directors,
                        employees, consultants, licensors, agents, and representatives from and against any and all
                        third- party claims, losses, liabilities, damages, and/or costs (including reasonable attorney
                        fees and costs) arising from your access to or use of RR Mart or the Services, violation of
                        these Terms of Use, or infringement of any intellectual property or other rights of RR or any
                        third-party. RR will notify you promptly of any such claim, loss, liability, or demand, and in
                        addition to the foregoing, you agree to provide RR with reasonable assistance, at their expense,
                        in defending any such claim, loss, liability, damage, or cost.
                     </p>
                  </li>
                  <li>
                     <p>
                        To the fullest extent permitted by law, in no event shall RR or any of its directors, officers,
                        employees, agents or content or service providers (collectively, the <b> “RR Representatives”
                        </b>) be liable to you for any direct, indirect, special, incidental, consequential, exemplary,
                        special, remote or punitive damage, including, but not limited to damages for loss of profits,
                        goodwill, use, data or other intangible losses arising from, or directly or indirectly related
                        to, the use of, or the inability to use, RR Mart or the content, materials and functions related
                        thereto, the Services,&nbsp;provision of information via RR Mart, lost business, even if such RR
                        Representatives have been advised of the possibility of such damages.
                     </p>
                  </li>
                  <li>
                     <p>
                        In no event shall RR Representatives be liable for:
                     </p>
                     <ul>
                        <li>
                           <p>the use or inability to use RR Mart and/or the Services;</p>
                        </li>
                        <li>
                           <p>any content posted, transmitted, exchanged or received by or on behalf of any user or
                              other person on or through RR Mart;</p>
                        </li>
                        <li>
                           <p>any unauthorized access to or alteration of your transmissions of sensitive personal
                              information or other user data; or</p>
                        </li>
                        <li>
                           <p>any other matter relating to RR Mart or the Services.</p>
                        </li>
                     </ul>
                  </li>
                  <li>
                     <p>
                        RR is neither liable nor responsible for any actions or inactions of the other users of RR Mart
                        or any breach of conditions, representations or warranties by them. RR is not obligated to
                        mediate or resolve any dispute or disagreement amongst two or more users of RR Mart.
                     </p>
                  </li>
                  <li>
                     <p>
                        None of the directors, officials or employees of RR shall be personally liable for any action in
                        connection with RR Mart or the Services.
                     </p>
                  </li>
               </ul>
               <p></p>
            </li>

            <li><span class="font-weight-bolder">ACCESS OUTSIDE THE REPUBLIC OF INDIA</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        RR makes no representation that the content on RR Mart is appropriate to be used or accessed
                        outside the Republic of India. Any users who use or access RR Mart from outside the Republic of
                        India, do so at their own risk and are responsible for compliance with the laws of such
                        jurisdiction. These Terms of Use do not constitute, nor may these Terms of Use be used for or in
                        connection with any promotional activities or solicitation by anyone in any jurisdiction in
                        which such promotional activities or solicitation are not authorized or to any person to whom it
                        is unlawful to promote or solicit.
                     </p>
                  </li>
               </ul>
               <p></p>
            </li>

            <li><span class="font-weight-bolder">TERM AND TERMINATION</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        These Terms of Use shall be effective from the date of their publication on RR Mart.
                     </p>
                  </li>
                  <li>
                     <p>
                        RR reserves the right to terminate the Services in the event of breach of any terms contained in
                        these Terms of Use, misrepresentation of information, any unlawful activity by you or if RR is
                        unable to verify or authenticate any information submitted by you.
                     </p>
                  </li>
                  <li>
                     <p>
                        You may terminate these Terms of Use at any time, provided that you discontinue any further use
                        of RR Mart or Services. However, any such termination shall not cancel your obligation to pay
                        for a product purchased on RR Mart, or any other obligation which has accrued, or is unfulfilled
                        and relates to the period, prior to termination.
                     </p>
                  </li>
               </ul>
               <p></p>
            </li>
            <li><span class="font-weight-bolder">FORCE MAJEURE</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        RR will not be held responsible for any delay or failure to comply with its obligations if the
                        delay or failure arises from any cause which is beyond RR’s reasonable control.
                     </p>
                  </li>
               </ul>
               <p></p>
            </li>
            <li><span class="font-weight-bolder">WAIVER</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        No provision in these Terms of Use will be deemed waived and no breach excused, unless such
                        waiver or consent is in writing and signed by RR. Any consent by RR to, or waiver of your
                        breach, whether expressed or implied, will not constitute consent to, waiver of, or excuse for
                        any other different or subsequent breach.
                     </p>
                  </li>
               </ul>
               <p></p>
            </li>
            <li><span class="font-weight-bolder">SEVERABILITY</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        If any provision of these Terms of Use is held by a court of competent jurisdiction to be
                        unenforceable under applicable law, then such provision will be excluded from these Terms of Use
                        and the remainder of these Terms of Use will be interpreted as if such provision were so
                        excluded and will be enforceable in accordance with its terms; provided however that, in such
                        event, these Terms of Use will be interpreted so as to give effect, to the greatest extent
                        consistent with and permitted by applicable law, to the meaning and intention of the excluded
                        provision as determined by such court of competent jurisdiction.
                     </p>
                  </li>
               </ul>
               <p></p>
            </li>
            <li><span class="font-weight-bolder">GRIEVANCE REDRESSAL</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        You may submit any grievance with respect to RR Mart or the Services, including with respect to
                        any abuse on RR Mart including any discrepancies or grievances with respect to access or usage
                        of RR Mart in violation of these Terms of Use by any person, to the Grievance Officer at:
                     </p>
                     <table class="table table-sm table-bordered">
                        <tbody>
                           <tr class="table-active">
                              <th>Name</th>
                              <th>Email</th>
                           </tr>
                           <tr>
                              <td>Rajesh Kumar</td>
                              <td>
                                 <a href="mailto:customer.service@rrmart.in">customer.service@rrmart.in</a>
                              </td>
                           </tr>
                        </tbody>
                     </table>
                  </li>
               </ul>
               <p></p>
            </li>
            <li><span class="font-weight-bolder">GOVERNING LAW AND DISPUTE RESOLUTION</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        These Terms of Use, all transactions consummated between RR and you, and the relationship
                        between RR and you is governed by the laws of India, without reference to any conflict of laws
                        principles and with an exclusive jurisdiction to the courts of Mumbai.
                     </p>
                  </li>
               </ul>
               <p></p>
            </li>
            <li><span class="font-weight-bolder">AMENDMENT</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        These Terms of Use are subject to amendments and modifications and may be updated from time to
                        time, without any advance notice. You are requested to regularly review the Terms of Use as
                        available on RR Mart. You relationship with RR Mart will be governed by the most current version
                        of these Terms of Use, as published on RR Mart.
                     </p>
                  </li>
               </ul>
               <p></p>
            </li>
            <li><span class="font-weight-bolder">MISCELLANEOUS</span><br>
               <p>
               </p>
               <ul>
                  <li>
                     <p>
                        In addition to these Terms of Use, you will also ensure that you are in compliance with the
                        terms and conditions of the third parties, such as bank offers terms and conditions, brand
                        promotional offers, whose links, if any, are contained/embedded in the Services. You agree that
                        RR will not be liable for any transaction between itself and any such third parties.
                     </p>
                  </li>
                  <li>
                     <p>
                        These Terms of Use supersede all previous oral and written terms and conditions (if any)
                        communicated to you by RR, for the use of RR Mart, and the rights and liabilities with respect
                        to any Services to be provided by RR shall be limited to the scope of these Terms of Use.
                     </p>
                  </li>
               </ul>
               <p></p>
            </li>
            <li><span class="font-weight-bolder">NODAL OFFICER</span><br>
               <table class="table table-sm table-bordered mt-2">
                  <tbody>
                     <tr class="table-active">
                        <th>Name</th>
                        <th>Designation</th>
                        <th>Email</th>
                     </tr>
                     <tr>
                        <td>Sandeep Kumar</td>
                        <td>Director</td>
                        <td>
                           <a href="mailto:sandeep@raptureretails.com">sandeep@raptureretails.com</a>
                        </td>
                     </tr>
                  </tbody>
               </table>
            </li>

         </ol>
      </div>
   </div>
   <%@include file="./menu/footer.jsp"%>

      <%@include file="./menu/sidenav.jsp"%>
   <!-- Navmenu END -->
      <!-- Bootstrap core JavaScript -->
      <script src="/app/vendor/jquery/jquery.min.js"></script>
      <script src="/app/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
      <!-- slick Slider JS-->
      <script type="text/javascript" src="/app/vendor/slick/slick.min.js"></script>
      <!-- Sidebar JS-->
      <script type="text/javascript" src="/app/vendor/sidebar/hc-offcanvas-nav.js"></script>
      <!-- Custom scripts for all pages-->
      <script src="/app/js/osahan.js"></script>
      <script src="/app/vendor/preloader/js/jquery.preloader.min.js"></script>
      <script src="/app/js/globalscript.js"></script>


      <script>

         $(function () {

            

         });
      </script> 
</body>

</html>