<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">

<head>
  <title>RRMart - T & C</title>
      <%@include file="./menu/head.jsp"%>
   <style>
      ul,ol{
         padding-left: 15px;
      }
      #content p{
         text-align: justify;
      }
   </style>
</head>

<body>
   
   <div class="osahan-help">
      <div class="p-3 border-bottom bg-white">
         <div class="d-flex align-items-center">
            <a class="font-weight-bold text-danger text-decoration-none" href="/terms">
               <i class="icofont-rounded-left back-page"></i></a>
            <h6 class="font-weight-bold m-0 ml-3 ">Terms & Conditions</h6>
            <a class="toggle ml-auto" href="#"><i class="icofont-navigation-menu"></i></a>
         </div>
      </div>
   </div>
   <div class="p-3 mb-5" id="content">
      <h4 class="mb-3 text-center">Terms & Conditions</h4>
      <p>The terms and conditions of sale as set out herein (“ Terms of Sale”) constitute an agreement between the
         person/ entity listed as seller (“we”, “us” or “our”) on the portal and its corresponding mobile application
         (collectively, “RR Mart”) and you (“ you” or “your”) and govern your purchase of the products (“Product(s)”)
         from us on or through RR Mart. By placing an order for any Product with us or making a purchase of Product, you
         expressly agree to be bound by these Terms of Sale.</p>
      <p>These Terms of Sale are in addition to various agreements, Service Terms, Privacy Policy, Terms of Use and all
         other policies of RR Mart. These Terms of Sale constitute an electronic record within the meaning of the
         applicable law. This electronic record is generated by a computer system and does not require any physical or
         digital signatures.</p>
      <ol>
         <li><span class="font-weight-bolder">Our Contract of Sale</span><br>
            <p></p>
            <ul>
               <li>
                  <p>Listing and display of a Product by us on RR Mart is our invitation to you to make an offer for
                     purchase of such Product. Likewise, the placement of an order on RR Mart by you is your offer to
                     buy the Product(s) from us.</p>
               </li>
               <li>
                  <p>Once you have placed an order with us for purchase of a Product, you will receive an e-mail
                     confirming receipt of your order and containing the details of your order (the “Order
                     Confirmation”). The Order Confirmation is merely an acknowledgement that we have received your
                     order and does not signify our acceptance of your offer.</p>
               </li>
               <li>
                  <p>We only accept your offer and conclude the contract of sale for a Product ordered by you, when the
                     Product is shipped or dispatched to you and an e-mail confirmation is sent to you that the Product
                     has been shipped or dispatched to you (the “Shipment Confirmation”). We reserve the right, at our
                     sole discretion, to refuse or cancel any order for any reason whatsoever before sending Shipment
                     Confirmation to you.</p>
               </li>
               <li>
                  <p>You acknowledge that there may be certain Products in your order whose actual quantity may not be
                     known at the time of order placement (for example, fruits, vegetables, etc.). Such Products will
                     therefore be invoiced based on the exact weight at the time of packaging and upon dispatch, our
                     Shipment Confirmation will reflect such marginal variance in the quantity of the Product as against
                     your original order and relevant adjustment in the invoice amount.</p>
               </li>
               <li>
                  <p>If your order is dispatched in more than one package, you may receive separate Shipment
                     Confirmations for each package, and each Shipment Confirmation and corresponding dispatch will
                     conclude a separate contract of sale between you and us for the Product(s) specified in that
                     Shipment Confirmation.</p>
               </li>
               <li>
                  <p>Your contract is with us and you confirm that the Product(s) ordered by you are purchased for your
                     internal / personal purpose and not for re-sale or business purpose. Please note that we sell
                     Products only in quantities which correspond to the usual requirements of an average household.
                     This applies both to the number of Products ordered within a single order and the placing of
                     several orders for the same Product where the individual orders comprise a quantity typical for a
                     normal household.</p>
               </li>
               <li>
                  <p>You can cancel your order for a Product at no cost at any time before we send the Shipment
                     Confirmation relating to that Product.</p>
               </li>
               <li>
                  <p>All orders placed on RR Mart are subject to the availability of such Product, our acceptance of
                     your offer as per the above and your continued adherence to these Terms of Sale.</p>
               </li>
            </ul>
         </li>
         <li><span class="font-weight-bolder">Return and Refund</span><br>
            <p></p>
            <ul>
               <li>
                  <p>Please review the Returns Policy and Refund Policy of RR Mart, which applies to Products sold by
                     us.</p>
               </li>
            </ul>
         </li>
         <li><span class="font-weight-bolder">Product Availability</span><br>
            <p></p>
            <ul>
               <li>
                  <p>We list availability information for the Products on the relevant webpage of RR Mart. Beyond what
                     we say on that webpage or otherwise on RR Mart, we cannot be more specific about availability.
                     Please note that dispatch estimates are just that. They are not guaranteed dispatch times and
                     should not be relied upon as such. As we process your order, you will be informed by e-mail if any
                     Products you order turn out to be unavailable or out of stock.</p>
               </li>
            </ul>
         </li>
         <li><span class="font-weight-bolder">Product Pricing</span><br>
            <p></p>
            <ul>
               <li>
                  <p>All prices are listed in Indian Rupees. Price, as displayed, is inclusive of all applicable taxes.
                  </p>
               </li>
               <li>
                  <p>Products in your shopping cart of RR Mart will reflect the most recent price as displayed on the
                     Product’s information webpage on RR Mart. Please note that this price may differ from the price
                     shown for the Product when you first placed it in your shopping cart. Placing a Product in your
                     shopping cart does not reserve the price shown at that time. It is also possible that a Product’s
                     price may decrease between the time you place it in your shopping cart and the time you place the
                     order.</p>
               </li>
               <li>
                  <p>Subject to paragraph 1.4 above, the prices mentioned at the time of ordering will be the prices
                     charged on the date of the delivery. Although prices of most of the Products do not fluctuate on a
                     daily basis but prices of some of the Products (such as fresh food, vegetables, etc.) do change on
                     a daily basis. In case the prices are higher or lower on the date of delivery, no additional
                     charges will be collected or refunded, as the case may be, at the time of the delivery of the
                     order, except as set out in paragraph 1.4 above.</p>
               </li>
            </ul>
         </li>
         <li><span class="font-weight-bolder">Licenses</span><br>
            <p></p>
            <ul>
               <li>
                  <p>You acknowledge that there may be licenses/permissions required under the applicable laws to use,
                     purchase or otherwise possess certain Product(s). You will be solely responsible for obtaining such
                     licenses/permissions and complying with the terms of such licenses/permissions.</p>
               </li>
            </ul>
         </li>
         <li><span class="font-weight-bolder">Taxes</span><br>
            <p></p>
            <ul>
               <li>
                  <p>You shall be responsible for payment of all fees/costs/charges associated with the purchase of
                     Products from us and you agree to bear any and all applicable taxes.</p>
               </li>
            </ul>
         </li>
         <li><span class="font-weight-bolder">Eligibility</span><br>
            <p></p>
            <ul>
               <li>
                  <p>Only persons who can enter into legally binding contracts as per Indian Contract Act, 1872, i.e.
                     persons who are 18 years of age or older, are of sound mind, and are not disqualified from entering
                     into contracts by any law, can use RR Mart and place an order with us. If you are a minor i.e.
                     under the age of 18 years, you may purchase the Product on RR Mart only with the involvement of a
                     parent or guardian.</p>
               </li>
            </ul>
         </li>
         <li><span class="font-weight-bolder">Limitation of Liability</span><br>
            <p></p>
            <ul>
               <li>
                  <p>In no event, our aggregate liability, if any, that is proven and ordered by a court of competent
                     jurisdiction pursuant to a claim by you or person acting on your behalf, shall extend beyond the
                     refund of money charged from you for purchases made pursuant to an order under which such liability
                     has arisen and been established. We will not be responsible for any business loss (including loss
                     of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) or any
                     other indirect or consequential loss that is not reasonably foreseeable to both you and us when a
                     contract for the sale of Product by us to you was formed.</p>
               </li>
            </ul>
         </li>
         <li><span class="font-weight-bolder">Amendments</span><br>
            <p></p>
            <ul>
               <li>
                  <p>We reserve the right to make changes to our policies, and these Terms of Sale at any time. You will
                     be subject to the policies and Terms of Sale in force at the time you order Product from us, unless
                     any change to those policies or these Terms of Sale is required to be made by law or government
                     authority (in which case it will apply to orders previously placed by you). If any of these
                     conditions is deemed invalid, void, or for any reason unenforceable, that condition will be deemed
                     severable and will not affect the validity and enforceability of any remaining condition.</p>
               </li>
            </ul>
         </li>
         <li><span class="font-weight-bolder">Force Majeure</span><br>
            <p></p>
            <ul>
               <li>
                  <p>We will not be held responsible for any delay or failure to comply with its obligations if the
                     delay or failure arises from any cause which is beyond our reasonable control.</p>
               </li>
            </ul>
         </li>
         <li><span class="font-weight-bolder">Waiver</span><br>
            <p></p>
            <ul>
               <li>
                  <p>No provision in these Terms of Sale will be deemed waived and no breach excused, unless such waiver
                     or consent is in writing and signed by us. Our consent to, or waiver of your breach, whether
                     expressed or implied, will not constitute consent to, waiver of, or excuse for any other different
                     or subsequent breach.</p>
               </li>
            </ul>
         </li>
         <li><span class="font-weight-bolder">Governing Law and Dispute Resolution</span><br>
            <p></p>
            <ul>
               <li>
                  <p>These Terms of Sale, all transactions consummated between you and us, and our relationship with you
                     is governed by the laws of India, without reference to any conflict of laws principles and with an
                     exclusive jurisdiction to the courts of Mumbai.</p>
               </li>
            </ul>
         </li>
         <li><span class="font-weight-bolder">Miscellaneous</span><br>
            <p></p>
            <ul>
               <li>
                  <p>In addition to these Terms of Sale, you will also ensure that you are in compliance with the terms
                     and conditions of the third parties, such as bank offers terms and conditions, brand promotional
                     offers, whose links, if any, are contained/embedded in the Service Terms or Terms of Use.</p>
               </li>
               <li>
                  <p>These Terms of Sale supersede all previous oral and written terms and conditions (if any)
                     communicated to you by us, for the purchase of Product.</p>
               </li>
            </ul>
         </li>
      </ol>
   </div>

   <%@include file="./menu/footer.jsp"%>

      <%@include file="./menu/sidenav.jsp"%>
   <!-- Navmenu END -->
      <!-- Bootstrap core JavaScript -->
      <script src="/app/vendor/jquery/jquery.min.js"></script>
      <script src="/app/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
      <!-- slick Slider JS-->
      <script type="text/javascript" src="/app/vendor/slick/slick.min.js"></script>
      <!-- Sidebar JS-->
      <script type="text/javascript" src="/app/vendor/sidebar/hc-offcanvas-nav.js"></script>
      <!-- Custom scripts for all pages-->
      <script src="/app/js/osahan.js"></script>
      <script src="/app/vendor/preloader/js/jquery.preloader.min.js"></script>
      <script src="/app/js/globalscript.js"></script>


      <script>

         $(function () {

            

         });
      </script> 
</body>

</html>